Repository BadwaterBay/intelli-trip-planner, pull requests merged in 2020-05, with the labels that each got.

#14 Replaces var with let in app.js
  src/html/app/route-optimization/app.js
Labels: PR: review accepted

#17 Fixes #16. Maintenance/replace php with html
  .gitignore
  package-lock.json
  src/html/app/route-optimization/index.html
  src/html/app/route-optimization/index.php
  src/html/app/route-optimization/place_API_KEY_in_this_directory
  src/html/common/config.php
  src/html/common/footer.php
  src/html/common/head.php
  src/html/common/header.php
  src/html/common/htmlTag.php
  src/html/common/methods.php
  src/html/common/navbar.php
  src/html/css/bootstrap.css
  src/html/css/prism.css
  src/html/css/prism.min.css
  src/html/js/prism.js
  src/html/js/prism.min.js
  src/html/js/script.js
  src/html/js/script.min.js
  src/old/Sample.py
  src/old/app.js
  src/old/app_1.js
  src/old/app_2.js
  src/old/app_3.js
  src/old/getDistanceMatrix.js
  src/old/getPermutations.js
  src/old/package-lock.json
  src/old/package.json
  src/old/report.20191104.175900.4871.0.001.json
  src/old/report.20191104.175954.5026.0.001.json
  src/old/report.20191104.180335.5129.0.001.json
Labels: PR: review needed, complexity: 2

#23 Updated README, including goal, tasks,and contributors
  README.md
Labels: type: documentation

#30 Roll back to using php to load api key and added JQuery and Bootstrap.js as necessary infrastructure
  src/app/app.js
  src/app/index.php
  src/app/place_API_KEY_in_this_directory
Labels: PR: review accepted

#32 Enhancement/rewrite for loops
  src/app/app.js
Labels: PR: review needed, complexity: 2, lang: javascript, type: enhancement

#33 Fix #1: Add radio button: return to origin at the end with other minor updates
  .gitignore
  src/app/app.js
  src/app/index.php
  src/app/place_API_KEY_in_this_directory
Labels: PR: review needed

#35 Fix #34 Init npm & add eslint, prettier, and husky precommit hook
  .eslintignore
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .prettierignore
  .prettierrc.js
  README.md
  package-lock.json
  package.json
  src/app/app.js
  src/app/styles.scss
  src/data/EXPLANATION.md
  src/old/app_promiseStyle.js
Labels: PR: review accepted
